SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

USE Ajay_DB;
GO

ALTER TABLE dbo.tblAI_Users WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_Roles WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_UserRoles WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_KnowledgeBase WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_AgentConfigurations WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_ChatSessions WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_ChatMessages WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_Documents WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_DocumentChunks WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_Embeddings WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_ApplicationLogs WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_ErrorLogs WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE dbo.tblAI_AuditLogs WITH CHECK CHECK CONSTRAINT ALL;
GO

DBCC CHECKCONSTRAINTS WITH ALL_CONSTRAINTS;
GO
